### ISSUE TITLE
Unicode Errors

### ISSUE THREAD

**Issue by ryanbuckner** [FlyingDiver/Indigo-BondHome#7]
I have 2 devices that use commas and 2 rooms that have commas.  They were throwing errors in v 0.2.0.  When I removed the commas, the errors went away: 

_```
Aug 20, 2021 at 1:54:34 PM
   Reloading plugin "Bond Home 0.2.0"
   Stopping plugin "Bond Home 0.2.0" (pid 9980)
   Stopped plugin "Bond Home 0.2.0"
   Starting plugin "Bond Home 0.2.0" (pid 11558)
   Started plugin "Bond Home 0.2.0"
   Bond Home Error                 Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 244, in runConcurrentThread
  File "plugin.py", line 199, in doDeviceStartup
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 5: ordinal not in range(128)

   Bond Home Error                 plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
   Bond Home Error                 Error in plugin execution runConcurrentThread:
```_

**Comment by FlyingDiver** [comment]
u'\u2019' is the unicode "right single quotation mark".  Your commas were probably fine.

**Comment by ryanbuckner** [comment]
> u'\u2019' is the unicode "right single quotation mark". Your commas were probably fine.

Big mistake on my side. I did use 2 right quotation marks, not commas.   For example : Ryan's Room  and Ryan's Ceiling Fan Lights

**Comment by FlyingDiver** [comment]
Yeah, if you use the plain ASCII single quote, you'll be fine.
